using Microsoft.Data.SqlClient;
using System.Data;

namespace Disconnected
{
    internal class Program
    {
        static void Main(string[] args)
        {
            string _ConStr = "Data Source=(LocalDB)\\MSSQLLocalDB;Initial Catalog=IETDb;Integrated Security=True";

            #region SELECT Query
            /* SqlConnection con = new SqlConnection(_ConStr);


             SqlDataAdapter da = new SqlDataAdapter("SELECT * FROM EMPLOYEE1", con);

             da.MissingSchemaAction = MissingSchemaAction.AddWithKey;

             DataSet ds = new DataSet();
             da.Fill(ds, "Employee1"); // reader the records and fill DataSet table.

             foreach (DataRow row in ds.Tables["Employee1"].Rows)
             {
                 int id = Convert.ToInt32(row["EId"]);
                 string nm = row["EName"].ToString();
                 string add = row["EAddress"].ToString();
                 Console.WriteLine($"Id: {id}, Name: {nm}, Address: {add}");
             }*/
            #endregion

            #region INSERT Query
            SqlConnection con = new SqlConnection(_ConStr);
            SqlDataAdapter da = new SqlDataAdapter("SELECT * FROM EMPLOYEE1", con);

            da.MissingSchemaAction = MissingSchemaAction.AddWithKey;

            SqlCommandBuilder builder = new SqlCommandBuilder(da);

            DataSet ds = new DataSet();
            da.Fill(ds, "Employee1");
            //ds.GetXml()

            Console.WriteLine("Enter ID:");
            int id = Convert.ToInt32(Console.ReadLine());
            Console.WriteLine("Enter Name:");
            string nm = Console.ReadLine();
            Console.WriteLine("Enter Address:");
            string add = Console.ReadLine();

            DataRow newRow = ds.Tables["Employee1"].NewRow();
            newRow["EId"] = id;
            newRow["EName"] = nm;
            newRow["EAddress"] = add;

            ds.Tables["Employee1"].Rows.Add(newRow);

            da.Update(ds, "Employee1");//Insert Query is generated by CommandBuilder
            Console.WriteLine("Record inserted!");


            #endregion
        }
    }
}
